### ISSUE TITLE
Invalid path calculation in gradle-composite\build.gradle on Windows

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-umbrella#30] opened 2017-04-28 12:43 UTC
I observed the following gradle path calculation problem when setting up the Xtext development environment on Windows:
![gradle_path_problem](https://cloud.githubusercontent.com/assets/20393472/25529022/ab45c546-2c20-11e7-8bcd-dc1c71e939ec.png)
One possible solution would be to adapt the xtext-umbrella\releng\gradle-composite\build.gradle file to use forward slashes in the rootDir:
![gradle_path_problem_solution](https://cloud.githubusercontent.com/assets/20393472/25529100/f3d3685e-2c20-11e7-8bd7-9e515735a6df.png)

**Comment by cdietrich** [comment] 2017-04-28 12:45
can you please share the diff as text. i wonder why i could not reproduce this on my windows.
maybe there was a change in gradle?

**Comment by miklossy** [comment] 2017-04-28 12:49
[30-Gradle-path-calculation-problem.txt](https://github.com/eclipse/xtext-umbrella/files/964360/30-Gradle-path-calculation-problem.txt)

**Comment by cdietrich** [comment] 2017-04-28 12:52
hmm i just have it a try on my machine with the current setup and the pref is generated like this

```
connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)
connection.project.dir=C:\work\xtext-master\git\xtext-umbrella\releng\gradle-composite
project.path=\:org.eclipse.xtext.builder.standalone
```

and the properties looks like

```
git.clone.xtext.lib.location=C:\\work\\xtext-master\\git\\xtext-lib
git.clone.xtext.core.location=C:\\work\\xtext-master\\git\\xtext-core
git.clone.xtext.extras.location=C:\\work\\xtext-master\\git\\xtext-extras
git.clone.xtext.idea.location=C:\\work\\xtext-master\\git\\xtext-idea
git.clone.xtext.xtend.location=C:\\work\\xtext-master\\git\\xtext-xtend
git.clone.xtext.web.location=C:\\work\\xtext-master\\git\\xtext-web
```
how does it look like on your machine

**Comment by cdietrich** [comment] 2017-04-28 12:52
@oehme can you tell us how the prefs should look like?

**Comment by oehme** [comment] 2017-04-28 13:09
@cdietrich Buildship should read any valid path, but of course if you want to use a backslash in a preference file, you'd have to escape it.

Buildship itself will always generate Unix separators so the file is the same independently of which platform it runs on.

**Comment by cdietrich** [comment] 2017-04-28 13:15
i tried it again and i dont get any errors. what do i need to do to get your error @miklossy

**Comment by miklossy** [comment] 2017-04-28 14:15
I just did a fresh setup: downloaded and executed the eclipse-inst-win64.exe and the problem still exists. I get the following Exception when I right click on the org.eclipse.xtext project and execute Gradle->Refresh Project.  
![gradle_path_problem_buildship_exception_stacktrace](https://cloud.githubusercontent.com/assets/20393472/25532465/c60c71e2-2c2d-11e7-8684-be468803d843.png)

@cdietrich Could you specify more exact which file contents are you interested in?

**Comment by cdietrich** [comment] 2017-04-28 14:19
git it @kthoms can you please merge

**Comment by cdietrich** [comment] 2017-05-24 08:00
was fixed in 2.12

**Comment by cdietrich** [comment] 2017-07-20 10:03
@kthoms @miklossy looks like the absolute path thingy you built no longer works with current versions of buildship see https://github.com/eclipse/buildship/issues/528#issuecomment-316657032

can you have a look if there is another solution that works on windows as well?

**Comment by cdietrich** [comment] 2017-07-20 10:28
did some work on https://github.com/eclipse/xtext-umbrella/commit/6dc77069456f085d1543e712362501a0947e3ac5
needs to be tested on windows

**Comment by cdietrich** [comment] 2017-08-02 04:32
merged the pull request. still need a second confirmation on windows @miklossy @kthoms

**Comment by miklossy** [comment] 2017-08-04 13:09
I have just created an Xtext development environment (via a fresh Oomph Setup) on Windows10 and could import all the projects without any problems.

I would suggest to consider this issue as solved.

**Closed** 2017-08-04 13:29 UTC
